# Working with Arrays

### 1. Run the following cells:

In [1]:
import numpy as np

In [2]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [4]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [7]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Slice the first column of the 2-D array. 

In [9]:
print(array_2D[:,0])

[20 43 11]


### 3. Slice the last column of the 2-D array

In [11]:
print(array_2D[:,-1])

[60 87 55]


### 4. Slice the second row of the 2-D array

In [15]:
print(array_2D[1,:])

[43 54 65 76 87]


### 5. Slice the last two columns of the 2-nd row of the 2-D array

In [19]:
print(array_2D[:,-2:])

[[50 60]
 [76 87]
 [44 55]]


### 6. Slice the 2-nd row of the 2-D array excluding the last two columns

In [21]:
print(array_2D[1,:-2])

[43 54 65]


### 7. Slice everything excluding the first row and last column of the 2-D array

In [23]:
print(array_2D[1:,:-1])

[[43 54 65 76]
 [11 22 33 44]]


### 8. Slice the 1st, 3rd and 5th columns of the 2-D array
   (<b>Hint</b>: Take advantage of the [start:stop:step] suntax of indices)

In [25]:
print(array_2D[:,::2])

[[20 40 60]
 [43 65 87]
 [11 33 55]]


### 9. Slice the first columns of both matrices in the 3-D array
   (<b>Hint</b>: The syntax for the indices of the 3-D array is the following: [subarray, row, column])

In [29]:
print(array_3D[:,:,0])

[[ 1 11]
 [11 51]]


### 10. Slice every other column of both matrices in the 3-D array

In [31]:
print(array_3D[:,:,::2])

[[[ 1  3  5]
  [11 31 51]]

 [[11 13 15]
  [51 53  5]]]


### 11. Use conditional slicing to check if the individual elements of each array satisfy a given condition (e.g. greater than 10)

In [33]:
print(array_1D[:] > 10)

[False  True  True  True  True]


In [35]:
print(array_2D[:] > 10)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [37]:
print(array_3D[:] > 10)

[[[False False False False False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True False]]]


### 12. Use conditional slicing to display which individual elements of each array satisfy this condition

In [39]:
print(array_1D[array_1D[:] > 10])

[11 12 13 14]


In [41]:
print(array_2D[array_2D[:] > 10])

[20 30 40 50 60 43 54 65 76 87 11 22 33 44 55]


In [43]:
print(array_3D[array_3D[:] > 10])

[11 21 31 41 51 11 12 13 14 15 51 52 53 54]


### 13. Add a second condition and disaply which individual elements satisfy both (e.g. greater than 10 and odd)
   (<b>Hint</b>: Odd numbers leave a remainder of 1, when dividing by 2. Hence, we can use "%" to express this condition.)

In [55]:
print(array_1D[(array_1D[:] > 10) & (array_1D[:] % 2 == 1)])

[11 13]


In [57]:
print(array_2D[(array_2D[:] > 10) & (array_2D[:] % 2 == 1)])

[43 65 87 11 33 55]


In [59]:
print(array_3D[(array_3D[:] > 10) & (array_3D[:] % 2 == 1)])

[11 21 31 41 51 11 13 15 51 53]


### 13. Loosen up the requirements, so that either condition works
   (<b>Hint</b>: We just need to go from <i>condition_1</i> <b> and </b> <i>condition_2</i> to <i>condition_1</i> <b> or </b> <i>condition_2</i>)

In [61]:
print(array_1D[(array_1D[:] > 10) | (array_1D[:] % 2 == 1)])

[11 12 13 14]


In [63]:
print(array_2D[(array_2D[:] > 10) | (array_2D[:] % 2 == 1)])

[20 30 40 50 60 43 54 65 76 87 11 22 33 44 55]


In [65]:
print(array_3D[(array_3D[:] > 10) | (array_3D[:] % 2 == 1)])

[ 1  3  5 11 21 31 41 51 11 12 13 14 15 51 52 53 54  5]


### 14. Call the first row of the first 2-D array in the 3-D array in 3 different ways:
    A) Use precise indices for both dimensions. 
    B) Use a precise index for one dimension and a slice for the second dimension. 
    C) Uses slices (from the origin, up to the second value) for both dimensions. 

In [67]:
print(array_3D[0,0,:])

[1 2 3 4 5]


In [69]:
print(array_3D[0,:1,:])

[[1 2 3 4 5]]


In [71]:
print(array_3D[:1,:1,:])

[[[1 2 3 4 5]]]


### 15. Check the shapes of the 3 different notations calling the same values

In [73]:
print(array_3D[0,0,:].shape)

(5,)


In [75]:
print(array_3D[0,:1,:].shape)

(1, 5)


In [77]:
print(array_3D[:1,:1,:].shape)

(1, 1, 5)


### 16. Since the last two outputs contain excess dimensions, use the squeeze function to reduce them

In [79]:
print(array_3D[0,:1,:].squeeze())

[1 2 3 4 5]


In [81]:
print(array_3D[:1,:1,:].squeeze())

[1 2 3 4 5]


### 17. Now check the shapes of the reduced outputs

In [83]:
print(array_3D[0,:1,:].squeeze().shape)

(5,)


In [85]:
print(array_3D[:1,:1,:].squeeze().shape)

(5,)
